gradle/dependency-management.gradle

Upgrade to Spring Session Data Geode 2.0.3.RELEASE

---

gradle/dependency-management.gradle

Upgrade to Spring Session for MongoDB 2.2.0.RC2.

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.2.0.RC1

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.1.6.RELEASE

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.1.7.RELEASE

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.2.1.RELEASE

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.1.8.RELEASE

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.2.2.RELEASE

---

gradle/dependency-management.gradle

Upgrade Spring Session Data Geode to 2.3.0.M2

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.3.0.RC1

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.1.9.RELEASE

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.2.3.RELEASE

---

gradle/dependency-management.gradle

Upgrade to Spring Session Data Geode 2.3.0.RC2

---

gradle/dependency-management.gradle

Upgrade Spring Session Data Geode to 2.3.0.RELEASE

---

gradle/dependency-management.gradle

Upgrade Spring Session Data Geode to 2.2.4.RELEASE

---

gradle/dependency-management.gradle

Upgrade Spring Session Data Geode to 2.1.10.RELEASE

---

gradle/dependency-management.gradle

Upgrade spring-session-data-geode to 2.4.0-M1

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.2.6.RELEASE

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.1.12.RELEASE

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.3.2.RELEASE

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.2.7.RELEASE

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.3.3.RELEASE

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.4.1

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.3.4.RELEASE

---

gradle/dependency-management.gradle

Upgrade to Spring Session for Apache Geode 2.4.2

---

gradle.properties

Build against Spring Session 3.0 snapshots
